# Generated by Django 3.0.7 on 2020-06-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200612_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user',
        ),
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionentry',
            name='num_servings',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
