# Generated by Django 3.0.7 on 2020-06-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200612_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
