# Generated by Django 3.0.7 on 2020-06-15 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20200615_1105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'name')},
        ),
    ]
