# Generated by Django 3.0.7 on 2020-06-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200615_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionentry',
            name='num_servings',
            field=models.FloatField(default=1),
        ),
    ]
