# Generated by Django 3.0.7 on 2020-06-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200615_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionentry',
            name='meal',
        ),
    ]
