# Generated by Django 3.0.7 on 2020-06-16 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_nutritionentry_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionentry',
            name='carb_grams',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionentry',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionentry',
            name='fat_grams',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionentry',
            name='protein_grams',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
