# Generated by Django 3.0.7 on 2020-06-17 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionentry',
            name='time_entered',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 17, 1, 13, 18, 629875, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
