# Generated by Django 3.0.7 on 2020-06-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_nutritionentry_time_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_hours_eating_window',
            field=models.IntegerField(default=8),
        ),
    ]
