# Generated by Django 3.0.7 on 2020-06-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_stopeatingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='fiber_grams',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritionentry',
            name='fiber_grams',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
