# Generated by Django 3.0.7 on 2020-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200617_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='include_meditation_in_app',
            field=models.BooleanField(default=False),
        ),
    ]
