# Generated by Django 3.0.7 on 2020-06-18 23:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_userprofile_include_meditation_in_app'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StopEatingEvent',
            new_name='MeditationEvent',
        ),
    ]
