# Generated by Django 3.0.7 on 2020-06-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200627_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='plan',
        ),
    ]
