# Generated by Django 3.0.7 on 2020-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_userprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('aggressive', 'Aggressive Weight Loss'), ('moderate', 'Moderate Weight Loss'), ('slow', 'Slow Weight Loss'), ('maintenance', 'Weight Maintenance')], default='slow', max_length=50),
        ),
    ]
