# Generated by Django 3.0.7 on 2020-06-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userprofile_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='num_hours_eating_window',
        ),
    ]
