# Generated by Django 3.0.7 on 2020-07-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_remove_userprofile_num_hours_eating_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('super_charged', 'Super Charged'), ('aggressive', 'Aggressive Weight Loss'), ('moderate', 'Moderate Weight Loss'), ('slow', 'Slow Weight Loss'), ('maintenance', 'Weight Maintenance')], default='slow', max_length=50),
        ),
        migrations.CreateModel(
            name='DailyTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('exercise', models.CharField(choices=[('gold', 'gold'), ('green', 'green'), ('yellow', 'yellow'), ('red', 'red')], default='red', max_length=20)),
                ('pe_ratio', models.CharField(choices=[('gold', 'gold'), ('green', 'green'), ('yellow', 'yellow'), ('red', 'red')], default='red', max_length=20)),
                ('protein_total', models.CharField(choices=[('gold', 'gold'), ('green', 'green'), ('yellow', 'yellow'), ('red', 'red')], default='red', max_length=20)),
                ('meditation', models.CharField(choices=[('gold', 'gold'), ('green', 'green'), ('yellow', 'yellow'), ('red', 'red')], default='red', max_length=20)),
                ('eating_window', models.CharField(choices=[('gold', 'gold'), ('green', 'green'), ('yellow', 'yellow'), ('red', 'red')], default='red', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
