# Generated by Django 3.0.7 on 2020-07-15 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_auto_20200715_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytracking',
            unique_together={('user', 'date')},
        ),
    ]
